#!/usr/bin/env python3
"""Generate Mosaic Runner's original 8x8 player atlas header."""
from pathlib import Path
import sys

PIXELS = ("..BBBB..", ".BBBBBB.", "OOOOOOOO", "OWOOOOWO", "OOOOOOOO", ".OOOOOO.", ".OO..OO.", "OO....OO")
VALUES = {".": 0, "B": 1, "O": 2, "W": 3}
body = ", ".join(str(VALUES[pixel]) for row in PIXELS for pixel in row)
OUTPUT = "// Generated by tools/generate_atlas.py; SPDX-License-Identifier: Apache-2.0\n#pragma once\n#include <stdint.h>\nconstexpr uint8_t kPlayerAtlas[64] = {" + body + "};\n"
target = Path(__file__).resolve().parents[1] / "src/generated_atlas.hpp"
if "--check" in sys.argv:
    raise SystemExit(0 if target.is_file() and target.read_text() == OUTPUT else 1)
target.write_text(OUTPUT)
